name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '* */1 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install
      run: |
        npm install

    - name: Deploy
      env:	#添加环境变量
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          HEWEATHER_KEY: ${{ secrets.HEWEATHER_KEY }}
      run: npm run weather
