name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
       - cron: '0 0/3 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist

    - name: Build After
      run: curl --location --request GET "http://www.pushplus.plus/send?token=e40ac3db842c47d0b8690144c760accb&title=%E6%B5%8 B%E8%AF%95&content=hello%20world!"
