name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '* */1 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install
      run: |
        npm install

    - name: Deploy
      run: cross-env PUSHPLUS_TOKEN=${{ secrets.PUSHPLUS_TOKEN }}  node ./script/index.js
